image:
  tag: ${image_tag}
host: ${host}
replicaCount: ${app_replicas}.0
minAvailable: 1
externalMongodbUrl: ${mongodb_uri}
externalMongodbOplogUrl: ${mongodb_oplog_uri}
smtp:
  enabled: true
  host: ${smtp_host}
  port: ${smtp_port}
  username: ${smtp_username}
  password: ${smtp_password}


mongodb:
  mongodbDatabase: ${mongodb_database}
  mongodbUsername: ${mongodb_username}
  mongodbPassword: ${mongodb_password}
  mongodbRootPassword: ${mongodb_root_password}
  replicaSet:
    enabled: true
    replicas:
      arbiter: 1
      secondary: 1
      pdb:
        minAvailable:
          arbiter: 1
          secondary: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: "/"
  tls:
    - hosts:
        - ${host}
      secretName: ${tls_secret_name}
