image:
  tag: ${image_tag}
host: ${host}
replicaCount: ${app_replicas}.0
minAvailable: 1
externalMongodbUrl: ${mongodb_uri}
externalMongodbOplogUrl: ${mongodb_oplog_uri}
smtp:
  enabled: true
  host: ${smtp_host}
  port: ${smtp_port}
  username: ${smtp_username}
  password: ${smtp_password}

resources:
  limits:
    cpu: 750m
    memory: 1600Mi
  requests:
    cpu: 500m
    memory: 800Mi

mongodb:
  mongodbDatabase: ${mongodb_database}
  mongodbUsername: ${mongodb_username}
  mongodbPassword: ${mongodb_password}
  mongodbRootPassword: ${mongodb_root_password}
  replicaSet:
    enabled: true
    replicas:
      arbiter: 1
      secondary: 1
      pdb:
        minAvailable:
          arbiter: 1
          secondary: 1
  resources:
    limits:
      cpu: 200m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 1000Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 5M
  path: "/"
  tls:
    - hosts:
        - ${host}
      secretName: ${tls_secret_name}
